#ifndef GY26_COMMON_H

#define GY26_COMMON_H

#define I2C_JUSTIFYLEFT_LO 0xE0
#define I2C_JUSTIFYRIGHT_LO 0x70
#define I2C_JUSTIFYRIGHT_HI 0x7F

#define REG_DECLINATION 0x03
#define CMD_GET_COMPASS 0x31
#define CMD_GET_TEMPERATURE 0x35
#define CMD_RESET_CODE_1 0xA0
#define CMD_RESET_CODE_2 0xAA
#define CMD_RESET_CODE_3 0xA5
#define CMD_START_CALIBRATION 0xC0
#define CMD_END_CALIBRATION 0xC1
#define CMD_FACTORY_RESET 0xC5

#endif //GY26_COMMON_H